default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: rails_testing_dev

test:
  <<: *default
  database: rails_testing_test

production:
  <<: *default
  database: rails_testing_prod